/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAL.CauHoiDAL;
import DAL.DeThiDAL;
import DAL.LuaChonDAL;
import DTO.CauHoiDTO;
import DTO.DeThiDTO;
import DTO.LuaChonDTO;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class CauHoiGUI extends javax.swing.JPanel {

    /**
     * Creates new form DeThiGUI
     */
    public CauHoiGUI() {
        initComponents();
        loadDataToTable();
        groupButton();
        setDeThi();
    }

    public void setDeThi() {
        int maDe = DeThiGUI.maDeThiDuocChon;
        String tenDe = DeThiGUI.tenDeThiDuocChon;
        txtDeThi.setText(maDe + "-" + tenDe);
    }

    private void groupButton() {
        ButtonGroup btng = new ButtonGroup();
        btng.add(rbtnA);
        btng.add(rbtnB);
        btng.add(rbtnC);
        btng.add(rbtnD);
        rbtnA.setSelected(true);
    }

    private void clearCauHoi() {
        txtMaCauHoi.setText("");
        txtCauHoiText.setText("");
        txtA.setText("");
        txtB.setText("");
        txtC.setText("");
        txtD.setText("");

    }

    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tableCauHoi.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("Mã câu hỏi");
        model.addColumn("Mã đề");
        model.addColumn("Câu hỏi");
        int maDe = DeThiGUI.maDeThiDuocChon;
        List<CauHoiDTO> lstCauHoi = CauHoiDAL.layDanhSachCauHoiTheoMaDe(maDe);

        for (CauHoiDTO ch : lstCauHoi) {
            Object[] rowData = {ch.getMaCauHoi(), ch.getMaDe(), ch.getCauHoiText()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaCauHoi = new javax.swing.JTextField();
        txtDeThi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCauHoiText = new javax.swing.JTextArea();
        rbtnA = new javax.swing.JRadioButton();
        rbtnB = new javax.swing.JRadioButton();
        rbtnC = new javax.swing.JRadioButton();
        rbtnD = new javax.swing.JRadioButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtB = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtD = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtC = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCauHoi = new javax.swing.JTable();

        setBackground(new java.awt.Color(139, 233, 253));
        setForeground(new java.awt.Color(139, 233, 253));

        jPanel1.setBackground(new java.awt.Color(139, 233, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin danh mục câu hỏi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(40, 42, 54))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(40, 42, 54));

        jLabel2.setText("Mã câu hỏi:");

        txtMaCauHoi.setEnabled(false);

        jLabel3.setText("Đề thi:");

        jLabel4.setText("Câu hỏi:");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtCauHoiText.setColumns(20);
        txtCauHoiText.setRows(5);
        jScrollPane2.setViewportView(txtCauHoiText);

        rbtnA.setText("A");

        rbtnB.setText("B");

        rbtnC.setText("C");

        rbtnD.setText("D");

        txtB.setColumns(20);
        txtB.setRows(5);
        jScrollPane7.setViewportView(txtB);

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane4.setViewportView(txtA);

        txtD.setColumns(20);
        txtD.setRows(5);
        jScrollPane5.setViewportView(txtD);

        txtC.setColumns(20);
        txtC.setRows(5);
        jScrollPane6.setViewportView(txtC);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtMaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnD)
                            .addComponent(rbtnB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnA)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua)
                            .addComponent(rbtnB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXoa)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnD)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnC))
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );

        tableCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã đề thi", "Tên đề thi", "Tổng điểm"
            }
        ));
        tableCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCauHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCauHoi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int maDeThi = Integer.parseInt(txtDeThi.getText().split("-")[0]);
        String cauHoi = txtCauHoiText.getText();
        String luaChonTextA = txtA.getText();
        boolean laLuaChonDungA = false;
        if (rbtnA.isSelected()) {
            laLuaChonDungA = true;
        }

        String luaChonTextB = txtB.getText();
        boolean laLuaChonDungB = false;
        if (rbtnB.isSelected()) {
            laLuaChonDungB = true;
        }

        String luaChonTextC = txtC.getText();
        boolean laLuaChonDungC = false;
        if (rbtnC.isSelected()) {
            laLuaChonDungC = true;
        }

        String luaChonTextD = txtD.getText();
        boolean laLuaChonDungD = false;
        if (rbtnD.isSelected()) {
            laLuaChonDungD = true;
        }
        if ("".equals(cauHoi)) {
            JOptionPane.showMessageDialog(this, "Câu hỏi không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ("".equals(luaChonTextA) || "".equals(luaChonTextB) || "".equals(luaChonTextC) || "".equals(luaChonTextD)) {
            JOptionPane.showMessageDialog(this, "Nội dung lựa chọn không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CauHoiDTO ch = new CauHoiDTO(maDeThi, cauHoi);
        if (CauHoiDAL.themCauHoi(ch)) {
            int maCauHoi = CauHoiDAL.layMaCauHoiLonNhat();
            if (maCauHoi != 0) {
                LuaChonDTO luaChonA = new LuaChonDTO(maCauHoi, luaChonTextA, laLuaChonDungA);
                LuaChonDTO luaChonB = new LuaChonDTO(maCauHoi, luaChonTextB, laLuaChonDungB);
                LuaChonDTO luaChonC = new LuaChonDTO(maCauHoi, luaChonTextC, laLuaChonDungC);
                LuaChonDTO luaChonD = new LuaChonDTO(maCauHoi, luaChonTextD, laLuaChonDungD);
                LuaChonDAL.themLuaChon(luaChonA);
                LuaChonDAL.themLuaChon(luaChonB);
                LuaChonDAL.themLuaChon(luaChonC);
                LuaChonDAL.themLuaChon(luaChonD);
            }
            JOptionPane.showMessageDialog(this, "Thêm câu hỏi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadDataToTable();
            clearCauHoi();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm câu hỏi thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = tableCauHoi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một câu hỏi để sửa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int maDeThi = Integer.parseInt(txtDeThi.getText().split("-")[0]);
        String cauHoi = txtCauHoiText.getText();
        String luaChonTextA = txtA.getText();
        boolean laLuaChonDungA = false;
        if (rbtnA.isSelected()) {
            laLuaChonDungA = true;
        }

        String luaChonTextB = txtB.getText();
        boolean laLuaChonDungB = false;
        if (rbtnB.isSelected()) {
            laLuaChonDungB = true;
        }

        String luaChonTextC = txtC.getText();
        boolean laLuaChonDungC = false;
        if (rbtnC.isSelected()) {
            laLuaChonDungC = true;
        }

        String luaChonTextD = txtD.getText();
        boolean laLuaChonDungD = false;
        if (rbtnD.isSelected()) {
            laLuaChonDungD = true;
        }
        if ("".equals(cauHoi)) {
            JOptionPane.showMessageDialog(this, "Câu hỏi không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ("".equals(luaChonTextA) || "".equals(luaChonTextB) || "".equals(luaChonTextC) || "".equals(luaChonTextD)) {
            JOptionPane.showMessageDialog(this, "Nội dung lựa chọn không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int maCauHoi = Integer.parseInt(txtMaCauHoi.getText());
        CauHoiDTO ch = new CauHoiDTO(maCauHoi, maDeThi, cauHoi);
        if (CauHoiDAL.capNhatCauHoi(ch)) {
            if (maCauHoi != 0) {
                List<LuaChonDTO> lstLuaChon = LuaChonDAL.layDanhSachLuaChonTheoMaCauHoi(maCauHoi);
                int maLuaChonA = lstLuaChon.get(0).getMaLuaChon();
                int maLuaChonB = lstLuaChon.get(1).getMaLuaChon();
                int maLuaChonC = lstLuaChon.get(2).getMaLuaChon();
                int maLuaChonD = lstLuaChon.get(3).getMaLuaChon();
                LuaChonDTO luaChonA = new LuaChonDTO(maLuaChonA, maCauHoi, luaChonTextA, laLuaChonDungA);
                LuaChonDTO luaChonB = new LuaChonDTO(maLuaChonB, maCauHoi, luaChonTextB, laLuaChonDungB);
                LuaChonDTO luaChonC = new LuaChonDTO(maLuaChonC, maCauHoi, luaChonTextC, laLuaChonDungC);
                LuaChonDTO luaChonD = new LuaChonDTO(maLuaChonD, maCauHoi, luaChonTextD, laLuaChonDungD);
                LuaChonDAL.capNhatLuaChon(luaChonA);
                LuaChonDAL.capNhatLuaChon(luaChonB);
                LuaChonDAL.capNhatLuaChon(luaChonC);
                LuaChonDAL.capNhatLuaChon(luaChonD);
            }
            JOptionPane.showMessageDialog(this, "Sửa câu hỏi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadDataToTable();
             clearCauHoi();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa câu hỏi thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableCauHoi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một câu hỏi để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int maCauHoi = Integer.parseInt(tableCauHoi.getValueAt(selectedRow, 0).toString());
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa câu hỏi này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            if (CauHoiDAL.xoaCauHoi(maCauHoi)) {

                JOptionPane.showMessageDialog(this, "Xóa câu hỏi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable();
                 clearCauHoi();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa câu hỏi thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tableCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCauHoiMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableCauHoi.getSelectedRow();
        if (selectedRow != -1) {
            String maCauHoi = tableCauHoi.getValueAt(selectedRow, 0).toString();
            String cauHoiText = tableCauHoi.getValueAt(selectedRow, 2).toString();
            txtMaCauHoi.setText(maCauHoi);
            txtCauHoiText.setText(cauHoiText);
            List<LuaChonDTO> lstLuaChon = LuaChonDAL.layDanhSachLuaChonTheoMaCauHoi(Integer.parseInt(maCauHoi));
            String luaChonTextA = lstLuaChon.get(0).getLuaChonText();
            boolean laLuaChonDungA = lstLuaChon.get(0).isLaLuaChonDung();
            String luaChonTextB = lstLuaChon.get(1).getLuaChonText();
            boolean laLuaChonDungB = lstLuaChon.get(1).isLaLuaChonDung();
            String luaChonTextC = lstLuaChon.get(2).getLuaChonText();
            boolean laLuaChonDungC = lstLuaChon.get(2).isLaLuaChonDung();
            String luaChonTextD = lstLuaChon.get(3).getLuaChonText();
            boolean laLuaChonDungD = lstLuaChon.get(3).isLaLuaChonDung();
            txtA.setText(luaChonTextA);
            rbtnA.setSelected(laLuaChonDungA);
            txtB.setText(luaChonTextB);
            rbtnB.setSelected(laLuaChonDungB);
            txtC.setText(luaChonTextC);
            rbtnC.setSelected(laLuaChonDungC);
            txtD.setText(luaChonTextD);
            rbtnD.setSelected(laLuaChonDungD);

        }
    }//GEN-LAST:event_tableCauHoiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnD;
    private javax.swing.JTable tableCauHoi;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextArea txtB;
    private javax.swing.JTextArea txtC;
    private javax.swing.JTextArea txtCauHoiText;
    private javax.swing.JTextArea txtD;
    private javax.swing.JTextField txtDeThi;
    private javax.swing.JTextField txtMaCauHoi;
    // End of variables declaration//GEN-END:variables
}
