
package GUI;

import DAL.DeThiDAL;
import DTO.DeThiDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class DeThiGUI extends javax.swing.JPanel {

    
    public DeThiGUI() {
        initComponents();
        loadDataToTable();
    }
    public static int maDeThiDuocChon;
    public static String tenDeThiDuocChon;
    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tableDeThi.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("Mã đề thi");
        model.addColumn("Tên đề thi");
        model.addColumn("Tổng điểm");
        List<DeThiDTO> lstDeThi = DeThiDAL.layDanhSachDeThi();

        for (DeThiDTO dt : lstDeThi) {
            Object[] rowData = {dt.getMaDe(), dt.getTenDe(), dt.getTongDiem()};
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaDeThi = new javax.swing.JTextField();
        txtTenDeThi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTongDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        btnThi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDeThi = new javax.swing.JTable();

        setBackground(new java.awt.Color(139, 233, 253));
        setForeground(new java.awt.Color(139, 233, 253));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 42, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH MỤC ĐỀ THI");

        jPanel1.setBackground(new java.awt.Color(139, 233, 253));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin danh mục đề thi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(40, 42, 54))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(40, 42, 54));

        jLabel2.setText("Mã đề thi:");

        txtMaDeThi.setEnabled(false);

        jLabel3.setText("Tên đề thi:");

        txtTongDiem.setText("10.00");

        jLabel4.setText("Tổng điểm:");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnChiTiet.setText("Chi Tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        btnThi.setText("Thi");
        btnThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSua)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnChiTiet)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnChiTiet)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTongDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnThi))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tableDeThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã đề thi", "Tên đề thi", "Tổng điểm"
            }
        ));
        tableDeThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDeThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDeThi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtTenDeThi.getText())) {
            JOptionPane.showMessageDialog(this, "Tên đề thi không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        float tongDiem = 0.0f;
        try {
            tongDiem = Float.parseFloat(txtTongDiem.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Tổng điểm phải là số thực!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String tenDeThi = txtTenDeThi.getText();
        DeThiDTO dt = new DeThiDTO(tenDeThi, tongDiem);
        if (DeThiDAL.themDeThi(dt)) {
            JOptionPane.showMessageDialog(this, "Thêm đề thi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadDataToTable();
            xoaDuLieu();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm đề thi thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableDeThi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đề thi để sửa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ("".equals(txtTenDeThi.getText())) {
            JOptionPane.showMessageDialog(this, "Tên đề thi không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        float tongDiem = 0.0f;
        try {
            tongDiem = Float.parseFloat(txtTongDiem.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Tổng điểm phải là số thực!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int maDeThi = Integer.parseInt(txtMaDeThi.getText());
        String tenDeThi = txtTenDeThi.getText();
        DeThiDTO dt = new DeThiDTO(maDeThi, tenDeThi, tongDiem);
        if (DeThiDAL.capNhatDeThi(dt)) {
            JOptionPane.showMessageDialog(this, "Sửa đề thi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            loadDataToTable();
            xoaDuLieu();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa đề thi thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableDeThi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đề thi để xóa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int maDeThi = Integer.parseInt(tableDeThi.getValueAt(selectedRow, 0).toString());
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa đề thi này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            if (DeThiDAL.xoaDeThi(maDeThi)) {

                JOptionPane.showMessageDialog(this, "Xóa đề thi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable();
                xoaDuLieu();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa đề thi thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    private void xoaDuLieu() {
        txtMaDeThi.setText("");
        txtTenDeThi.setText("");
        txtTongDiem.setText("");
    }
    private void tableDeThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDeThiMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableDeThi.getSelectedRow();
        if (selectedRow != -1) {
            String maDeThi = tableDeThi.getValueAt(selectedRow, 0).toString();
            String tenDeThi = tableDeThi.getValueAt(selectedRow, 1).toString();
            String tongDiem = tableDeThi.getValueAt(selectedRow, 2).toString();
            txtMaDeThi.setText(maDeThi);
            txtTenDeThi.setText(tenDeThi);
            txtTongDiem.setText(tongDiem);
        }
    }//GEN-LAST:event_tableDeThiMouseClicked

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableDeThi.getSelectedRow();
        if (selectedRow != -1) {
            int maDeThi = Integer.parseInt(tableDeThi.getValueAt(selectedRow, 0).toString());       
            String tenDeThi = tableDeThi.getValueAt(selectedRow, 1).toString();     
            maDeThiDuocChon = maDeThi;
            tenDeThiDuocChon = tenDeThi;
            GiaoDienChinh.frameGiaoDienChinh.hienThiCauHoiCuaDeThi();
        }
        else{
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một đề thi để xem chi tiết!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThiActionPerformed
        // TODO add your handling code here:
         int selectedRow = tableDeThi.getSelectedRow();
        if (selectedRow != -1) {
            int maDeThi = Integer.parseInt(tableDeThi.getValueAt(selectedRow, 0).toString());       
            String tenDeThi = tableDeThi.getValueAt(selectedRow, 1).toString();     
            maDeThiDuocChon = maDeThi;
            tenDeThiDuocChon = tenDeThi;
            System.out.println(SinhVienGUI.maSinhVienHienTai);
            if(SinhVienGUI.maSinhVienHienTai != null){
          GiaoDienChinh.frameGiaoDienChinh.hienThiBaiThi();
            }
            else{
            GiaoDienChinh.frameGiaoDienChinh.hienThiGiaoDienSinhVien();
            }
            
        }
        else{
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một đề thi để thi!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDeThi;
    private javax.swing.JTextField txtMaDeThi;
    private javax.swing.JTextField txtTenDeThi;
    private javax.swing.JTextField txtTongDiem;
    // End of variables declaration//GEN-END:variables
}
