/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAL.SinhVienDAL;
import DTO.SinhVienDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author huyng
 */
public class SinhVienGUI extends javax.swing.JPanel {
public static String maSinhVienHienTai;
public static String tenSinhVienHienTai;
public static String soDienThoaiHienTai;
    /**
     * Creates new form SinhVienGUI
     */
    public SinhVienGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSinhVien = new javax.swing.JPanel();
        panelThongTinSinhVien = new javax.swing.JPanel();
        btnVaoThi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTenSinhVien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        panelSinhVien.setBackground(new java.awt.Color(139, 233, 253));
        panelSinhVien.setForeground(new java.awt.Color(98, 114, 164));

        panelThongTinSinhVien.setBackground(new java.awt.Color(139, 233, 253));
        panelThongTinSinhVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(68, 71, 90), 10, true));

        btnVaoThi.setText("Vào thi");
        btnVaoThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaoThiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 42, 54));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THÔNG TIN SINH VIÊN");

        txtMaSinhVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaSinhVienKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(40, 42, 54));
        jLabel1.setText("Mã sinh viên:");

        txtTenSinhVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTenSinhVienKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(40, 42, 54));
        jLabel2.setText("Tên sinh viên:");

        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(40, 42, 54));
        jLabel3.setText("Số điện thoại:");

        javax.swing.GroupLayout panelThongTinSinhVienLayout = new javax.swing.GroupLayout(panelThongTinSinhVien);
        panelThongTinSinhVien.setLayout(panelThongTinSinhVienLayout);
        panelThongTinSinhVienLayout.setHorizontalGroup(
            panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinSinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinSinhVienLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinSinhVienLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVaoThi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelThongTinSinhVienLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(panelThongTinSinhVienLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelThongTinSinhVienLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThongTinSinhVienLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelThongTinSinhVienLayout.setVerticalGroup(
            panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinSinhVienLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addGroup(panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(panelThongTinSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addComponent(btnVaoThi)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout panelSinhVienLayout = new javax.swing.GroupLayout(panelSinhVien);
        panelSinhVien.setLayout(panelSinhVienLayout);
        panelSinhVienLayout.setHorizontalGroup(
            panelSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinhVienLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(panelThongTinSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        panelSinhVienLayout.setVerticalGroup(
            panelSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinhVienLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(panelThongTinSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaoThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaoThiActionPerformed
        String maSinhVien = txtMaSinhVien.getText();
        String tenSinhVien = txtTenSinhVien.getText();
        String soDienThoai = txtSoDienThoai.getText();
        if ("".equals(maSinhVien) || "".equals(tenSinhVien) || "".equals(soDienThoai)) {
            JOptionPane.showMessageDialog(this, "Thông tin sinh viên không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        maSinhVienHienTai = maSinhVien;
        tenSinhVienHienTai = tenSinhVien;
        soDienThoaiHienTai = soDienThoai;
        SinhVienDTO sv = new SinhVienDTO(maSinhVien, tenSinhVien, soDienThoai);
        SinhVienDAL.themSinhVien(sv);
        GiaoDienChinh.frameGiaoDienChinh.hienThiBaiThi();
     
    }//GEN-LAST:event_btnVaoThiActionPerformed

    private void txtMaSinhVienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSinhVienKeyTyped
        // TODO add your handling code here:
        if (txtMaSinhVien.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMaSinhVienKeyTyped

    private void txtTenSinhVienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenSinhVienKeyTyped
        // TODO add your handling code here:
        if(txtTenSinhVien.getText().length() >= 50){
            evt.consume();
        }
    }//GEN-LAST:event_txtTenSinhVienKeyTyped

    private void txtSoDienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyTyped
        // TODO add your handling code here:
        if (txtSoDienThoai.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSoDienThoaiKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVaoThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelSinhVien;
    private javax.swing.JPanel panelThongTinSinhVien;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenSinhVien;
    // End of variables declaration//GEN-END:variables
}
