/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAL.DeThiDAL;
import DAL.KetQuaThiDAL;
import DTO.DeThiDTO;
import DTO.XepHangDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyng
 */
public class XepHangGUI extends javax.swing.JPanel {

    /**
     * Creates new form XepHangGUI
     */
    public XepHangGUI() {
        initComponents();
        loadDataToTable();
    }
   private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tableXepHang.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("Mã sinh viên");
        model.addColumn("Tên sinh viên");
        model.addColumn("Số điện thoại");
        model.addColumn("Tên đề");
        
        model.addColumn("Điểm số đạt được");
        List<XepHangDTO> lstXepHang = KetQuaThiDAL.layDanhSachKetQuaThi();

        for (XepHangDTO xh : lstXepHang) {
            Object[] rowData = {xh.getMaSinhVien(), xh.getTenSinhVien(), xh.getSoDienThoai(), xh.getTenDe(), xh.getDiemSoDatDuoc()};
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableXepHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(139, 233, 253));

        tableXepHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Số điện thoại", "Tên đề", "Số câu trả lời đúng", "Số câu trả lời sai", "Số câu chưa làm", "Điểm số đạt được"
            }
        ));
        jScrollPane1.setViewportView(tableXepHang);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 42, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KẾT QUẢ THI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableXepHang;
    // End of variables declaration//GEN-END:variables
}
